"""Initial tables

Revision ID: 1c91972f1857
Revises:
Create Date: 2025-08-18 15:58:07.497804

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c91972f1857"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "join_date", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
    )
    op.create_table(
        "bans",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE")
        ),
        sa.Column("ban_reason", sa.String(200), nullable=True),
        sa.Column("banned_by", sa.Integer(), nullable=True),
        sa.Column("ban_date", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("unbanned_by", sa.Integer(), nullable=True),
        sa.Column("unban_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unban_reason", sa.String(200), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bans")
    op.drop_table("users")
    # ### end Alembic commands ###
